import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const read = (path) => readFile(new URL(path, import.meta.url), 'utf8')

test('multicenter overview promotes the interactive topology to the main workspace', async () => {
  const page = await read('../pages/multicenter/index.vue')

  assert.match(page, /class="multicenter-surface"/)
  assert.match(page, /class="multicenter-surface-header"/)
  assert.doesNotMatch(page, /MULTI-CENTER ORCHESTRATION/)
  assert.match(page, /class="multicenter-summary"/)
  assert.match(page, /class="topology-workspace"/)
  assert.match(page, /class="topology-cluster-rail"/)
  assert.match(page, /class="topology-stage"/)
  assert.match(page, /class="topology-inspector"/)
  assert.doesNotMatch(page, /拖动节点 · 滚轮缩放 · 拖动画布|点击中心或链路查看详情/)
  assert.doesNotMatch(page, /class="topology-stage-note"/)
})

test('multicenter removes redundant section copy and promotes headings', async () => {
  const page = await read('../pages/multicenter/index.vue')

  assert.doesNotMatch(page, /统一观察中心资源、跨中心链路与函数调度状态/)
  assert.doesNotMatch(page, /统一查看函数版本、运行环境与各算力中心的部署状态/)
  assert.doesNotMatch(page, /查看函数实例在各计算中心的就绪情况与资源占用/)
  assert.doesNotMatch(page, /跟踪跨中心迁移路径、执行状态与处理进度/)
  assert.doesNotMatch(page, /topology-live-pill|实时状态/)
  assert.doesNotMatch(page, /对比各处理阶段的响应耗时/)
  assert.doesNotMatch(page, /按调用顺序查看处理节点/)
  assert.doesNotMatch(page, /本次任务的中心路径与迁移上下文/)
  assert.doesNotMatch(page, /按时间顺序查看迁移处理阶段/)
  assert.match(page, /\.multicenter-heading-row h1\s*\{[^}]*font-size:\s*24px/s)
  assert.match(page, /\.topology-panel-header h2\s*\{[^}]*font-size:\s*19px/s)
  assert.match(page, /\.deployment-section-header h2\s*\{[^}]*font-size:\s*20px/s)
  assert.match(page, /\.workload-section-heading h2\s*\{[^}]*font-size:\s*20px/s)
  assert.match(page, /\.trace-panel-heading h3\s*\{[^}]*font-size:\s*16px/s)
  assert.match(page, /\.migration-detail-section-heading h3\s*\{[^}]*font-size:\s*16px/s)
})

test('topology stays draggable while keeping a non-drag selection alternative', async () => {
  const page = await read('../pages/multicenter/index.vue')

  assert.match(page, /layout:\s*'force'/)
  assert.match(page, /roam:\s*true/)
  assert.match(page, /draggable:\s*true/)
  assert.match(page, /symbol:\s*'circle'/)
  assert.match(page, /edgeLabel:\s*\{[\s\S]*show:\s*true[\s\S]*latency_ms/s)
  assert.match(page, /在线链路/)
  assert.match(page, /降级链路/)
  assert.match(page, /@chart-click="handleTopologyClick"/)
  assert.match(page, /class="cluster-rail-button"/)
  assert.match(page, /@click="selectCluster\(c\.id\)"/)
  assert.match(page, /ref="topologyChart"/)
  assert.match(page, /syncTopologySelection\(id\)/)
  assert.match(page, /type:\s*'select'/)
  assert.match(page, /aria-label="重置拓扑布局"/)
})

test('multicenter visual system is restrained, responsive, and accessible', async () => {
  const page = await read('../pages/multicenter/index.vue')

  assert.match(page, /\.topology-stage\s*\{[^}]*min-width:\s*0/s)
  assert.match(page, /\.topology-canvas\s*\{[^}]*height:\s*clamp\(/s)
  assert.match(page, /@media \(max-width:\s*1100px\)/)
  assert.match(page, /@media \(max-width:\s*720px\)/)
  assert.match(page, /@media \(prefers-reduced-motion:\s*reduce\)/)
  assert.match(page, /:focus-visible/)
  assert.doesNotMatch(page, /transition:\s*all/)
  assert.doesNotMatch(page, /edgeSymbol:\s*\['none',\s*'arrow'\]/)
})

test('function deployment merges function metadata and center status into one reusable board', async () => {
  const page = await read('../pages/multicenter/index.vue')

  assert.match(page, /const deploymentRows = computed(?:<[^>]+>)?\(/)
  assert.match(page, /function deploymentStatusLabel\(status: string\)/)
  assert.match(page, /function deploymentStatusClass\(status: string\)/)
  assert.match(page, /class="function-deployment-section"/)
  assert.match(page, /class="function-deployment-board"/)
  assert.match(page, /v-for="row in deploymentRows"/)
  assert.match(page, /class="deployment-function-info"/)
  assert.match(page, /class="deployment-centers"/)
  assert.match(page, /class="deployment-cell"/)
  assert.match(page, /v-if="row\.runtime"/)
  assert.match(page, /v-if="row\.image"/)
  assert.match(page, /:title="row\.image"/)
  assert.doesNotMatch(page, /row\.source_type/)
  assert.doesNotMatch(page, /联调服务正常/)
  assert.doesNotMatch(page, /<el-card v-for="fn in functions/)
  assert.doesNotMatch(page, /row\.cells\[c\.id\] \?\? '-'/)
  assert.match(page, /v-if="row\.status && row\.status !== 'ready'"/)
  assert.match(page, /v-if="deployment\.status !== 'ready'"[\s\S]*class="deployment-status"/)
  assert.match(page, /\.deployment-row\s*\{[^}]*grid-template-columns:\s*minmax\(300px, 0\.72fr\) minmax\(0, 1\.28fr\)/s)
  assert.match(page, /\.deployment-image code\s*\{[^}]*overflow:\s*hidden[^}]*text-overflow:\s*ellipsis[^}]*white-space:\s*nowrap/s)
  assert.match(page, /\.deployment-status\.is-ready/)
  assert.match(page, /\.deployment-status\.is-deploying/)
  assert.match(page, /\.deployment-status\.is-offline/)
  assert.match(page, /\.deployment-status\s*\{[^}]*font-size:\s*12px/s)
  assert.match(page, /\.deployment-summary\s*\{[^}]*font-size:\s*14px/s)
  assert.match(page, /\.deployment-summary strong\s*\{[^}]*font-size:\s*17px/s)
  assert.match(page, /@media \(max-width:\s*900px\)[\s\S]*\.deployment-row\s*\{[^}]*grid-template-columns:\s*1fr/s)
})

test('invocation tracking reuses the run-list table rhythm and status-aware hover feedback', async () => {
  const page = await read('../pages/multicenter/index.vue')

  assert.match(page, /function invocationRowClassName\(/)
  assert.match(page, /class="invocation-table-region"/)
  assert.match(page, /:row-class-name="invocationRowClassName"/)
  assert.doesNotMatch(page, /<el-table :data="invocations \?\? \[\]" border/)
  assert.match(page, /\.invocation-table-region :deep\(\.el-table th\.el-table__cell\)\s*\{[^}]*height:\s*48px[^}]*background:\s*#f7f9fc/s)
  assert.match(page, /\.invocation-table-region :deep\(\.el-table td\.el-table__cell\)\s*\{[^}]*height:\s*56px/s)
  assert.match(page, /tr\.invocation-row-status-running:hover > td\.el-table__cell\)\s*\{[^}]*background:\s*var\(--scnet-hover-bg\)/s)
  assert.match(page, /tr\.invocation-row-status-success:hover > td\.el-table__cell\)\s*\{[^}]*background:\s*var\(--scnet-hover-success-bg\)/s)
  assert.match(page, /tr\.invocation-row-status-failed:hover > td\.el-table__cell\)\s*\{[^}]*background:\s*var\(--scnet-hover-danger-bg\)/s)
  assert.match(page, /tr\.invocation-row-status-(?:queued|pending):hover > td\.el-table__cell\)\s*\{[^}]*background:\s*var\(--scnet-hover-warning-bg\)/s)
  assert.doesNotMatch(page, /transition:\s*all/)
})

test('trace detail stays inside the viewport and keeps both detail panels scrollable', async () => {
  const page = await read('../pages/multicenter/index.vue')

  assert.match(page, /class="trace-detail-dialog"/)
  assert.match(page, /align-center/)
  assert.match(page, /class="trace-detail-shell"/)
  assert.match(page, /class="trace-summary"/)
  assert.match(page, /const traceChartHeight = computed\(/)
  assert.match(page, /class="trace-detail-grid"/)
  assert.match(page, /class="trace-chart-panel"/)
  assert.match(page, /class="trace-stage-list"/)
  assert.doesNotMatch(page, /<el-table :data="trace\.spans"/)
  assert.doesNotMatch(page, /调用阶段瀑布/)
  assert.doesNotMatch(page, /25%/)
  assert.match(page, /:global\(\.trace-detail-dialog\)\s*\{[^}]*max-height:\s*min\(680px, calc\(100vh - 40px\)\)[^}]*overflow:\s*hidden/s)
  assert.match(page, /:global\(\.trace-detail-dialog \.el-dialog__body\)\s*\{[^}]*min-height:\s*0[^}]*overflow:\s*hidden/s)
  assert.match(page, /\.trace-chart-canvas\s*\{[^}]*overflow-y:\s*auto/s)
  assert.match(page, /\.trace-stage-list\s*\{[^}]*overflow-y:\s*auto/s)
  assert.match(page, /\.trace-summary dt\s*\{[^}]*font-size:\s*13px/s)
  assert.match(page, /\.trace-summary dd\s*\{[^}]*font-size:\s*15px/s)
  assert.match(page, /\.trace-stage-meta\s*\{[^}]*overflow-wrap:\s*anywhere/s)
  assert.match(page, /\.trace-panel-heading > span\s*\{[^}]*font-size:\s*13px/s)
})

test('workload migration uses structured center rows and a bounded event detail', async () => {
  const page = await read('../pages/multicenter/index.vue')

  assert.match(page, /class="workload-migration-section"/)
  assert.match(page, /class="workload-board"/)
  assert.match(page, /class="workload-row"/)
  assert.match(page, /class="workload-center-grid"/)
  assert.match(page, /class="migration-table-region"/)
  assert.match(page, /migrationRowClassName/)
  assert.match(page, /class="migration-progress-track"/)
  assert.match(page, /class="migration-detail-dialog"/)
  assert.match(page, /align-center/)
  assert.match(page, /append-to-body/)
  assert.match(page, /class="migration-detail-shell"/)
  assert.match(page, /class="migration-route-overview"/)
  assert.match(page, /class="migration-route-divider"/)
  assert.doesNotMatch(page, /class="migration-route-(?:bridge|arrow)"/)
  assert.doesNotMatch(page, /class="migration-route-label"/)
  assert.match(page, /class="migration-event-list"/)
  assert.match(page, /ev\.name \?\? ev\.event/)
  assert.match(page, /formatMigrationDataSize\(migDetail\.total_size_mb\)/)
  assert.doesNotMatch(page, /<el-descriptions/)
  assert.doesNotMatch(page, /<el-timeline/)
  assert.match(page, /:global\(\.migration-detail-dialog\)\s*\{[^}]*max-height:\s*min\(680px, calc\(100vh - 40px\)\)[^}]*overflow:\s*hidden/s)
  assert.match(page, /\.migration-event-list\s*\{[^}]*overflow-y:\s*auto/s)
  assert.match(page, /\.migration-detail-section-heading > span\s*\{[^}]*font-size:\s*13px/s)
  assert.match(page, /@media\s*\(max-width:\s*720px\)[\s\S]*?\.migration-detail-grid\s*\{[^}]*display:\s*block[^}]*overflow-y:\s*auto/s)
})

test('base chart forwards semantic chart selection events', async () => {
  const chart = await read('../components/BaseChart.vue')

  assert.match(chart, /defineEmits/)
  assert.match(chart, /chartClick/)
  assert.match(chart, /chart\.on\('click'/)
  assert.match(chart, /defineExpose/)
  assert.match(chart, /dispatchAction/)
  assert.match(chart, /role="img"/)
})
